-- 04 TRANSFORM STAGING INTO CORE
-- Step 1 counts, per column, values that fail type conversion and required columns that would be empty.
-- If anything fails, the load stops before touching core. Step 2 reloads core in foreign-key order.
USE KestrelSales;
GO
SET NOCOUNT ON;
DECLARE @run DATETIME2(0) = SYSDATETIME();

-- Step 1: conversion checks
INSERT INTO qa.conversion_check (run_at, table_name, column_name, is_required, failed_conversions, null_after_conversion, is_problem)
SELECT @run, x.table_name, x.column_name, x.is_required, x.failed, x.nulls,
       CASE WHEN x.failed > 0 OR (x.is_required = 1 AND x.nulls > 0) THEN 1 ELSE 0 END
FROM (
SELECT N'rep', N'rep_id', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(rep_id, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(rep_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(rep_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.reps
UNION ALL
SELECT N'rep', N'rep_name', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(rep_name, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(rep_name, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(rep_name, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.reps
UNION ALL
SELECT N'rep', N'team', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(team, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(team, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(team, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.reps
UNION ALL
SELECT N'rep', N'channel', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(channel, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(channel, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(channel, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.reps
UNION ALL
SELECT N'rep', N'hire_date', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(hire_date, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(hire_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(hire_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END)
FROM stg.reps
UNION ALL
SELECT N'rep', N'leave_date', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(leave_date, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(leave_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(leave_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END)
FROM stg.reps
UNION ALL
SELECT N'product', N'product_id', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(product_id, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(product_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(product_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.products
UNION ALL
SELECT N'product', N'product_name', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(product_name, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(product_name, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(product_name, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.products
UNION ALL
SELECT N'product', N'segment', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(segment, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(segment, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(segment, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.products
UNION ALL
SELECT N'product', N'list_mrr_gbp', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(list_mrr_gbp, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(list_mrr_gbp, NCHAR(13), N''))), N'')) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(list_mrr_gbp, NCHAR(13), N''))), N'')) IS NULL THEN 1 ELSE 0 END)
FROM stg.products
UNION ALL
SELECT N'lead', N'lead_id', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(lead_id, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(lead_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(lead_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.leads
UNION ALL
SELECT N'lead', N'created_date', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(created_date, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(created_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(created_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END)
FROM stg.leads
UNION ALL
SELECT N'lead', N'lead_source', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(lead_source, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(lead_source, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(lead_source, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.leads
UNION ALL
SELECT N'lead', N'segment', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(segment, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(segment, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(segment, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.leads
UNION ALL
SELECT N'lead', N'region', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(region, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(region, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(region, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.leads
UNION ALL
SELECT N'lead', N'assigned_rep_id', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(assigned_rep_id, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(assigned_rep_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(assigned_rep_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.leads
UNION ALL
SELECT N'lead', N'lead_status', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(lead_status, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(lead_status, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(lead_status, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.leads
UNION ALL
SELECT N'lead', N'lead_month', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(lead_month, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(lead_month, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(lead_month, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.leads
UNION ALL
SELECT N'lead', N'is_converted', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(is_converted, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_converted, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_converted, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.leads
UNION ALL
SELECT N'opportunity', N'opp_id', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(opp_id, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(opp_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(opp_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'lead_id', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(lead_id, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(lead_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(lead_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'rep_id', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(rep_id, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(rep_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(rep_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'team', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(team, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(team, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(team, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'channel', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(channel, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(channel, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(channel, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'lead_source', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(lead_source, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(lead_source, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(lead_source, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'segment', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(segment, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(segment, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(segment, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'region', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(region, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(region, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(region, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'product_id', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(product_id, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(product_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(product_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'product_name', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(product_name, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(product_name, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(product_name, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'list_mrr_gbp', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(list_mrr_gbp, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(list_mrr_gbp, NCHAR(13), N''))), N'')) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(list_mrr_gbp, NCHAR(13), N''))), N'')) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'discount_pct', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(discount_pct, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(discount_pct, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(discount_pct, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'discount_band', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(discount_band, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(discount_band, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(discount_band, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'mrr_gbp', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(mrr_gbp, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(mrr_gbp, NCHAR(13), N''))), N'')) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(mrr_gbp, NCHAR(13), N''))), N'')) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'contract_months', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(contract_months, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(contract_months, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(contract_months, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'tcv_gbp', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(tcv_gbp, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DECIMAL(12,2), NULLIF(LTRIM(RTRIM(REPLACE(tcv_gbp, NCHAR(13), N''))), N'')) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DECIMAL(12,2), NULLIF(LTRIM(RTRIM(REPLACE(tcv_gbp, NCHAR(13), N''))), N'')) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'created_date', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(created_date, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(created_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(created_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'quote_sent_date', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(quote_sent_date, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(quote_sent_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(quote_sent_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'credit_check_date', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(credit_check_date, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(credit_check_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(credit_check_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'close_date', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(close_date, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(close_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(close_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'created_month', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(created_month, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(created_month, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(created_month, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'close_month', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(close_month, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(close_month, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(close_month, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'close_year', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(close_year, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(close_year, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(close_year, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'outcome', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(outcome, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(outcome, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(outcome, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'stage', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(stage, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(stage, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(stage, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'lost_reason', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(lost_reason, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(lost_reason, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(lost_reason, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'is_closed', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(is_closed, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_closed, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_closed, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'is_won', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(is_won, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_won, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_won, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'date_error', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(date_error, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(date_error, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(date_error, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'sales_cycle_days', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(sales_cycle_days, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(sales_cycle_days, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(sales_cycle_days, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'rep_tenure_days', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(rep_tenure_days, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(rep_tenure_days, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(rep_tenure_days, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'rep_ramp_status', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(rep_ramp_status, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(rep_ramp_status, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(rep_ramp_status, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'install_date', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(install_date, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(install_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(install_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'install_wait_days', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(install_wait_days, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(install_wait_days, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(install_wait_days, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'install_wait_band', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(install_wait_band, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(install_wait_band, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(install_wait_band, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'order_status', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(order_status, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(order_status, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(order_status, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'is_install_resolved', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(is_install_resolved, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_install_resolved, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_install_resolved, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'is_cancelled_pre_install', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(is_cancelled_pre_install, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_cancelled_pre_install, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_cancelled_pre_install, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'cancel_date', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(cancel_date, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(cancel_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(cancel_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'activation_date', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(activation_date, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(activation_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(activation_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'customer_id', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(customer_id, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(customer_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(customer_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'churn_date', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(churn_date, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(churn_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(churn_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'eligible_90d', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(eligible_90d, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(eligible_90d, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(eligible_90d, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'churned_90d', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(churned_90d, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(churned_90d, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(churned_90d, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'opportunity', N'retained_90d_mrr', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(retained_90d_mrr, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(retained_90d_mrr, NCHAR(13), N''))), N'')) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(retained_90d_mrr, NCHAR(13), N''))), N'')) IS NULL THEN 1 ELSE 0 END)
FROM stg.opportunities
UNION ALL
SELECT N'customer', N'customer_id', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(customer_id, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(customer_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(customer_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'opp_id', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(opp_id, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(opp_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(opp_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'activation_date', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(activation_date, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(activation_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(activation_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'mrr_gbp', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(mrr_gbp, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(mrr_gbp, NCHAR(13), N''))), N'')) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(mrr_gbp, NCHAR(13), N''))), N'')) IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'contract_months', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(contract_months, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(contract_months, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(contract_months, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'churn_date', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(churn_date, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(churn_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(churn_date, NCHAR(13), N''))), N''), 23) IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'churn_reason', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(churn_reason, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(churn_reason, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(churn_reason, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'churn_date_error', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(churn_date_error, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(churn_date_error, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(churn_date_error, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'lead_source', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(lead_source, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(lead_source, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(lead_source, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'segment', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(segment, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(segment, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(segment, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'region', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(region, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(region, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(region, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'team', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(team, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(team, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(team, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'channel', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(channel, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(channel, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(channel, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'rep_id', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(rep_id, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(rep_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(rep_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'discount_pct', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(discount_pct, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(discount_pct, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(discount_pct, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'product_name', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(product_name, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(product_name, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(product_name, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'is_churned', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(is_churned, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_churned, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_churned, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'tenure_days', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(tenure_days, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(tenure_days, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(tenure_days, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'activation_month', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(activation_month, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(activation_month, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(activation_month, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'churn_month', 0,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(churn_month, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(churn_month, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(churn_month, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'eligible_90d', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(eligible_90d, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(eligible_90d, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(eligible_90d, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'customer', N'churned_90d', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(churned_90d, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(churned_90d, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(churned_90d, NCHAR(13), N''))), N''))) IS NULL THEN 1 ELSE 0 END)
FROM stg.customers
UNION ALL
SELECT N'quota', N'rep_id', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(rep_id, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(rep_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(rep_id, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.quotas
UNION ALL
SELECT N'quota', N'month', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(month, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(month, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(month, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.quotas
UNION ALL
SELECT N'quota', N'quota_mrr_gbp', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(quota_mrr_gbp, NCHAR(13), N''))), N'') IS NOT NULL AND TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(quota_mrr_gbp, NCHAR(13), N''))), N'')) IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(quota_mrr_gbp, NCHAR(13), N''))), N'')) IS NULL THEN 1 ELSE 0 END)
FROM stg.quotas
UNION ALL
SELECT N'quota', N'rep_name', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(rep_name, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(rep_name, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(rep_name, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.quotas
UNION ALL
SELECT N'quota', N'team', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(team, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(team, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(team, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.quotas
UNION ALL
SELECT N'quota', N'channel', 1,
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(channel, NCHAR(13), N''))), N'') IS NOT NULL AND NULLIF(LTRIM(RTRIM(REPLACE(channel, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END),
       SUM(CASE WHEN NULLIF(LTRIM(RTRIM(REPLACE(channel, NCHAR(13), N''))), N'') IS NULL THEN 1 ELSE 0 END)
FROM stg.quotas
) AS x (table_name, column_name, is_required, failed, nulls);

IF EXISTS (SELECT 1 FROM qa.conversion_check WHERE run_at = @run AND is_problem = 1)
BEGIN
    SELECT table_name, column_name, failed_conversions, null_after_conversion FROM qa.conversion_check WHERE run_at = @run AND is_problem = 1;
    THROW 50001, N'Type conversion problems found (listed above). Core tables were not changed.', 1;
END

-- Step 2: reload core in foreign-key order
BEGIN TRANSACTION;
DELETE FROM core.quota;
DELETE FROM core.customer;
DELETE FROM core.opportunity;
DELETE FROM core.lead;
DELETE FROM core.product;
DELETE FROM core.rep;
INSERT INTO core.rep (rep_id, rep_name, team, channel, hire_date, leave_date)
SELECT
    NULLIF(LTRIM(RTRIM(REPLACE(rep_id, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(rep_name, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(team, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(channel, NCHAR(13), N''))), N''),
    TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(hire_date, NCHAR(13), N''))), N''), 23),
    TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(leave_date, NCHAR(13), N''))), N''), 23)
FROM stg.reps;
INSERT INTO core.product (product_id, product_name, segment, list_mrr_gbp)
SELECT
    NULLIF(LTRIM(RTRIM(REPLACE(product_id, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(product_name, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(segment, NCHAR(13), N''))), N''),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(list_mrr_gbp, NCHAR(13), N''))), N''))
FROM stg.products;
INSERT INTO core.lead (lead_id, created_date, lead_source, segment, region, assigned_rep_id, lead_status, lead_month, is_converted)
SELECT
    NULLIF(LTRIM(RTRIM(REPLACE(lead_id, NCHAR(13), N''))), N''),
    TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(created_date, NCHAR(13), N''))), N''), 23),
    NULLIF(LTRIM(RTRIM(REPLACE(lead_source, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(segment, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(region, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(assigned_rep_id, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(lead_status, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(lead_month, NCHAR(13), N''))), N''),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_converted, NCHAR(13), N''))), N'')))
FROM stg.leads;
INSERT INTO core.opportunity (opp_id, lead_id, rep_id, team, channel, lead_source, segment, region, product_id, product_name, list_mrr_gbp, discount_pct, discount_band, mrr_gbp, contract_months, tcv_gbp, created_date, quote_sent_date, credit_check_date, close_date, created_month, close_month, close_year, outcome, stage, lost_reason, is_closed, is_won, date_error, sales_cycle_days, rep_tenure_days, rep_ramp_status, install_date, install_wait_days, install_wait_band, order_status, is_install_resolved, is_cancelled_pre_install, cancel_date, activation_date, customer_id, churn_date, eligible_90d, churned_90d, retained_90d_mrr)
SELECT
    NULLIF(LTRIM(RTRIM(REPLACE(opp_id, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(lead_id, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(rep_id, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(team, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(channel, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(lead_source, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(segment, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(region, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(product_id, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(product_name, NCHAR(13), N''))), N''),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(list_mrr_gbp, NCHAR(13), N''))), N'')),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(discount_pct, NCHAR(13), N''))), N''))),
    NULLIF(LTRIM(RTRIM(REPLACE(discount_band, NCHAR(13), N''))), N''),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(mrr_gbp, NCHAR(13), N''))), N'')),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(contract_months, NCHAR(13), N''))), N''))),
    TRY_CONVERT(DECIMAL(12,2), NULLIF(LTRIM(RTRIM(REPLACE(tcv_gbp, NCHAR(13), N''))), N'')),
    TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(created_date, NCHAR(13), N''))), N''), 23),
    TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(quote_sent_date, NCHAR(13), N''))), N''), 23),
    TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(credit_check_date, NCHAR(13), N''))), N''), 23),
    TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(close_date, NCHAR(13), N''))), N''), 23),
    NULLIF(LTRIM(RTRIM(REPLACE(created_month, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(close_month, NCHAR(13), N''))), N''),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(close_year, NCHAR(13), N''))), N''))),
    NULLIF(LTRIM(RTRIM(REPLACE(outcome, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(stage, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(lost_reason, NCHAR(13), N''))), N''),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_closed, NCHAR(13), N''))), N''))),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_won, NCHAR(13), N''))), N''))),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(date_error, NCHAR(13), N''))), N''))),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(sales_cycle_days, NCHAR(13), N''))), N''))),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(rep_tenure_days, NCHAR(13), N''))), N''))),
    NULLIF(LTRIM(RTRIM(REPLACE(rep_ramp_status, NCHAR(13), N''))), N''),
    TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(install_date, NCHAR(13), N''))), N''), 23),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(install_wait_days, NCHAR(13), N''))), N''))),
    NULLIF(LTRIM(RTRIM(REPLACE(install_wait_band, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(order_status, NCHAR(13), N''))), N''),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_install_resolved, NCHAR(13), N''))), N''))),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_cancelled_pre_install, NCHAR(13), N''))), N''))),
    TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(cancel_date, NCHAR(13), N''))), N''), 23),
    TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(activation_date, NCHAR(13), N''))), N''), 23),
    NULLIF(LTRIM(RTRIM(REPLACE(customer_id, NCHAR(13), N''))), N''),
    TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(churn_date, NCHAR(13), N''))), N''), 23),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(eligible_90d, NCHAR(13), N''))), N''))),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(churned_90d, NCHAR(13), N''))), N''))),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(retained_90d_mrr, NCHAR(13), N''))), N''))
FROM stg.opportunities;
INSERT INTO core.customer (customer_id, opp_id, activation_date, mrr_gbp, contract_months, churn_date, churn_reason, churn_date_error, lead_source, segment, region, team, channel, rep_id, discount_pct, product_name, is_churned, tenure_days, activation_month, churn_month, eligible_90d, churned_90d)
SELECT
    NULLIF(LTRIM(RTRIM(REPLACE(customer_id, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(opp_id, NCHAR(13), N''))), N''),
    TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(activation_date, NCHAR(13), N''))), N''), 23),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(mrr_gbp, NCHAR(13), N''))), N'')),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(contract_months, NCHAR(13), N''))), N''))),
    TRY_CONVERT(DATE, NULLIF(LTRIM(RTRIM(REPLACE(churn_date, NCHAR(13), N''))), N''), 23),
    NULLIF(LTRIM(RTRIM(REPLACE(churn_reason, NCHAR(13), N''))), N''),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(churn_date_error, NCHAR(13), N''))), N''))),
    NULLIF(LTRIM(RTRIM(REPLACE(lead_source, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(segment, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(region, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(team, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(channel, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(rep_id, NCHAR(13), N''))), N''),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(discount_pct, NCHAR(13), N''))), N''))),
    NULLIF(LTRIM(RTRIM(REPLACE(product_name, NCHAR(13), N''))), N''),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(is_churned, NCHAR(13), N''))), N''))),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(tenure_days, NCHAR(13), N''))), N''))),
    NULLIF(LTRIM(RTRIM(REPLACE(activation_month, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(churn_month, NCHAR(13), N''))), N''),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(eligible_90d, NCHAR(13), N''))), N''))),
    TRY_CONVERT(INT, TRY_CONVERT(DECIMAL(18,4), NULLIF(LTRIM(RTRIM(REPLACE(churned_90d, NCHAR(13), N''))), N'')))
FROM stg.customers;
INSERT INTO core.quota (rep_id, month, quota_mrr_gbp, rep_name, team, channel)
SELECT
    NULLIF(LTRIM(RTRIM(REPLACE(rep_id, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(month, NCHAR(13), N''))), N''),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(LTRIM(RTRIM(REPLACE(quota_mrr_gbp, NCHAR(13), N''))), N'')),
    NULLIF(LTRIM(RTRIM(REPLACE(rep_name, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(team, NCHAR(13), N''))), N''),
    NULLIF(LTRIM(RTRIM(REPLACE(channel, NCHAR(13), N''))), N'')
FROM stg.quotas;
COMMIT TRANSACTION;

INSERT INTO qa.load_log (run_at, table_name, staged_rows, loaded_rows)
SELECT @run, N'rep', (SELECT COUNT(*) FROM stg.reps), (SELECT COUNT(*) FROM core.rep)
UNION ALL
SELECT @run, N'product', (SELECT COUNT(*) FROM stg.products), (SELECT COUNT(*) FROM core.product)
UNION ALL
SELECT @run, N'lead', (SELECT COUNT(*) FROM stg.leads), (SELECT COUNT(*) FROM core.lead)
UNION ALL
SELECT @run, N'opportunity', (SELECT COUNT(*) FROM stg.opportunities), (SELECT COUNT(*) FROM core.opportunity)
UNION ALL
SELECT @run, N'customer', (SELECT COUNT(*) FROM stg.customers), (SELECT COUNT(*) FROM core.customer)
UNION ALL
SELECT @run, N'quota', (SELECT COUNT(*) FROM stg.quotas), (SELECT COUNT(*) FROM core.quota);
SELECT table_name, staged_rows, loaded_rows, CASE WHEN staged_rows = loaded_rows THEN 'OK' ELSE 'MISMATCH' END AS status
FROM qa.load_log WHERE run_at = @run;
GO
